### Numpy learning

##### Notes
- numpy written in C++
- only works with similar data types
- if you change a single element to float in a matrix name.dtype returns float64

In [1]:
#pip install numpy # un comment if required

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4])  #Needs a list

In [4]:
print(arr_1d)

[1 2 3 4]


In [5]:
arr_2d = np.array([1,2,3], [4,5,6]) # This gives error that "Field elements must be 2- or 3-tuples, got '4'"

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [6]:
arr_2d = np.array([[1,2,3], [4,5,6]])

In [7]:
print("2d array:", format(arr_2d))

2d array: [[1 2 3]
 [4 5 6]]


In [8]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print("2d array:", arr_2d )

2d array: [[1 2 3]
 [4 5 6]]


In [10]:
zeros = np.zeros([3,4])
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones = np.ones([2,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
full = np.full((2,3),5)
print(full)

[[5 5 5]
 [5 5 5]]


In [13]:
rand = np.random.random((3,3)) # random values vary from 0 to 1
print(rand)

[[0.94758998 0.39934804 0.82253308]
 [0.79186963 0.0963552  0.93856682]
 [0.85404156 0.8565878  0.91951828]]


In [14]:
rang = np.arange(1, 14, 3) # inclusive 1 non-inclusive 14 in step of 3
rang

array([ 1,  4,  7, 10, 13])

#### vector

In [15]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


#### matrix

In [16]:
mat = np.array([[1,2,3],
                [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


#### tensor or multi dimensional

In [17]:
tens = np.array([[[1,2], [3,4]],
                [[5,6],[7,8]]])
print(tens)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Properties

In [18]:
tens.shape # 2 element, 2 rows, 2 columns

(2, 2, 2)

In [19]:
tens.ndim # dimension 3-d

3

In [20]:
tens.size # total elements

8

In [21]:
tens.dtype # data type

dtype('int64')

In [22]:
mat.shape

(2, 3)

In [23]:
mat.ndim

2

In [25]:
print(mat)

[[1 2 3]
 [4 5 6]]


#### Operations

In [26]:
# transpose
trans = mat.transpose()
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
# flatten
flat = mat.flatten()
print(flat)

[1 2 3 4 5 6]


In [29]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [30]:
# ravel
raveled = mat.ravel()
print(raveled)

[1 2 3 4 5 6]


In [31]:
print(mat)

[[1 2 3]
 [4 5 6]]


###### flatten(): returns a copy of original arary. ravel() return a view( a reference) of the original array whenever possible. it does not allocate new memory unless it is  has to. 
###### because of this if you modify an element in ravel() ed array original array changes as well (because they share same memory data block)
###### ravel is faster and is just a view of the original array whenever possible

In [34]:
raveled[0] = 99
print(raveled)

[99  2  3  4  5  6]


In [35]:
print(mat)

[[99  2  3]
 [ 4  5  6]]


In [36]:
print(flat)

[1 2 3 4 5 6]


In [37]:
# reshape
reshaped = flat.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]
