### Numpy learning

##### Notes
- numpy written in C++
- only works with similar data types
- if you change a single element to float in a matrix name.dtype returns float64
- np.where also returns an array like np.array but for elements for which condition is true
- axis 0 is rows. axis 1 is columns

In [1]:
#pip install numpy # un comment if required

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4])  #Needs a list

In [4]:
print(arr_1d)

[1 2 3 4]


In [5]:
arr_2d = np.array([1,2,3], [4,5,6]) # This gives error that "Field elements must be 2- or 3-tuples, got '4'"

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [6]:
arr_2d = np.array([[1,2,3], [4,5,6]])

In [7]:
print("2d array:", format(arr_2d))

2d array: [[1 2 3]
 [4 5 6]]


In [8]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print("2d array:", arr_2d )

2d array: [[1 2 3]
 [4 5 6]]


In [10]:
zeros = np.zeros([3,4])
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones = np.ones([2,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
full = np.full((2,3),5)
print(full)

[[5 5 5]
 [5 5 5]]


In [13]:
rand = np.random.random((3,3)) # random values vary from 0 to 1
print(rand)

[[0.90509058 0.42693383 0.66211385]
 [0.30488775 0.72226544 0.64601456]
 [0.70007178 0.5336484  0.15272171]]


In [14]:
rang = np.arange(1, 14, 3) # inclusive 1 non-inclusive 14 in step of 3
rang

array([ 1,  4,  7, 10, 13])

#### vector

In [15]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


#### matrix

In [16]:
mat = np.array([[1,2,3],
                [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


#### tensor or multi dimensional

In [17]:
tens = np.array([[[1,2], [3,4]],
                [[5,6],[7,8]]])
print(tens)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Properties

In [18]:
tens.shape # 2 element, 2 rows, 2 columns

(2, 2, 2)

In [19]:
tens.ndim # dimension 3-d

3

In [20]:
tens.size # total elements

8

In [21]:
tens.dtype # data type

dtype('int64')

In [22]:
mat.shape

(2, 3)

In [23]:
mat.ndim

2

In [24]:
print(mat)

[[1 2 3]
 [4 5 6]]


#### Operations

In [25]:
# transpose
trans = mat.transpose()
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
# flatten
flat = mat.flatten()
print(flat)

[1 2 3 4 5 6]


In [27]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [28]:
# ravel
raveled = mat.ravel()
print(raveled)

[1 2 3 4 5 6]


In [29]:
print(mat)

[[1 2 3]
 [4 5 6]]


###### flatten(): returns a copy of original arary. ravel() return a view( a reference) of the original array whenever possible. it does not allocate new memory unless it is  has to. 
###### because of this if you modify an element in ravel() ed array original array changes as well (because they share same memory data block)
###### ravel is faster and is just a view of the original array whenever possible

In [30]:
raveled[0] = 99
print(raveled)

[99  2  3  4  5  6]


In [31]:
print(mat)

[[99  2  3]
 [ 4  5  6]]


In [32]:
print(flat)

[1 2 3 4 5 6]


In [33]:
# reshape
reshaped = flat.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


##### More operations

In [34]:
arr = np.arange(0,12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
# Basic slicing
print(arr[1:5]) # basic slicing. Starts from index 1 and end at index 5
print(arr[1:9:3]) # step of 3
print(arr[-4]) # negative indexing

[1 2 3 4]
[1 4 7]
8


In [36]:
# Two dimensinal array
print(mat)
mat.ndim

[[99  2  3]
 [ 4  5  6]]


2

In [37]:
# index by giving row and then column (start from 0th row 0th col)
# 2nd row 3rd column
print(mat[1,2]) 

6


In [38]:
# just second row
print(mat[1])

[4 5 6]


In [39]:
# second column
print(mat[:,1])

[2 5]


###### Sort

In [40]:
unsorted = np.array([4, 8, 6, 2, 6, 2, 7, 5, 2, 3, 9, 5 ])
print(np.sort(unsorted))  # original remains un changed
print(unsorted)

[2 2 2 3 4 5 5 6 6 7 8 9]
[4 8 6 2 6 2 7 5 2 3 9 5]


In [41]:
unsorted2d = unsorted.reshape(3,4)
print(unsorted2d)

[[4 8 6 2]
 [6 2 7 5]
 [2 3 9 5]]


In [42]:
# sort 2-d array
print(np.sort(unsorted2d, axis = 0)) # On columns - axis 0

[[2 2 6 2]
 [4 3 7 5]
 [6 8 9 5]]


In [43]:
print(np.sort(unsorted2d, axis = 1)) # On rows of unsorted2d - axis 1

[[2 4 6 8]
 [2 5 6 7]
 [2 3 5 9]]


##### Filter and Filter by mask

In [44]:
ranks = np.array([1,2,3,4,5,6,7,8,9,10])
evenRanks = ranks[ranks % 2 == 0]  # filter only even number
print(evenRanks)

[ 2  4  6  8 10]


In [45]:
# mask
# create mask
mask = ranks > 5
# Now use this directly in filter condition
bigRanks = ranks[mask]
print(bigRanks)

[ 6  7  8  9 10]


In [46]:
# what doses mask represent. Its actually an array of True/False
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

###### where
###### different then mask as 'where' gives same number of elements

In [47]:
# if greater than 5 then multiply it by 3 other wise same number
bigRanksTripled = np.where( ranks > 5, ranks * 3, ranks)
print(bigRanksTripled)

[ 1  2  3  4  5 18 21 24 27 30]


##### masked_where

In [48]:
# hide even numbers
onlyOdds = np.ma.masked_where(ranks % 2 == 0, ranks)
print(onlyOdds)

[1 -- 3 -- 5 -- 7 -- 9 --]


In [49]:
onlyOdds

masked_array(data=[1, --, 3, --, 5, --, 7, --, 9, --],
             mask=[False,  True, False,  True, False,  True, False,  True,
                   False,  True],
       fill_value=999999)

###### Adding and removing data

#### for merge or concatenate two arrays pass them as tuple to concatenate


In [50]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

merged = np.concatenate((arr1, arr2))

print(merged)
type(merged)

[1 2 3 4 5 6]


numpy.ndarray

In [51]:
# compatability
arr1.shape == arr2.shape

True

###### adding new row using vstack, column using hstack

In [52]:
a2darray = np.array([[1,2],[3,4]])
newRow = np.array([[5,6]])

print("Shape of a2darray: ", format(a2darray.shape))

threeRows = np.vstack((a2darray, newRow))
print(threeRows)
print("\n Shape of threeRows: ", format(threeRows.shape))


Shape of a2darray:  (2, 2)
[[1 2]
 [3 4]
 [5 6]]

 Shape of threeRows:  (3, 2)


In [53]:
# Now add a column using hstack
newCol = np.array([[7], [8], [9]])

withThirdColumn = np.hstack((threeRows, newCol))
print(withThirdColumn)
print("\n Shape of withThirdColumn ", format(withThirdColumn.shape))

[[1 2 7]
 [3 4 8]
 [5 6 9]]

 Shape of withThirdColumn  (3, 3)


##### delete 

In [54]:
deleted3DArray = np.delete(withThirdColumn, 1, 1) # here 1nth element from axis 1(column).
print(deleted3DArray)

[[1 7]
 [3 8]
 [5 9]]


In [55]:
#  axis 0 is rows
deleted0Axis = np.delete(withThirdColumn, 1, 0)
print(deleted0Axis)

[[1 2 7]
 [5 6 9]]


*Under the Hood*
Because NumPy arrays require contigous block of memory, *np.delete* cannot just "erase" a slot. It handles this 
by allocating a compeltely new array under the hood and copying over all the elements you decide to keep. This means
using np.delete repeatedly inside a loop can severely slow down code; when possible, it's better to use boolean masking
or slicing to select what you want to keep instead

###### Advanced operations 

In [58]:
# example data [serial_num, yr2000, yr2001, yr2002, yr2003]
sales_data = np.array([
    [1, 150, 180, 220, 250], # mcdonald
    [2, 120, 140, 160, 190], # beijing bites
    [3, 200, 230, 260, 300], # pizza hut
    [4, 180, 210, 240, 270], # burger king
    [5, 160, 185, 205, 230], # chai point
])

print(" Shape of data: ", sales_data.shape)

 Shape of data:  (5, 5)


In [60]:
print("===== Sales analysis ======")
print("\n")
print("Without indices", sales_data[:, 1:])  # first : means all reows, second : start from column 1


===== Sales analysis ======


Without indices [[150 180 220 250]
 [120 140 160 190]
 [200 230 260 300]
 [180 210 240 270]
 [160 185 205 230]]


In [62]:
# Total sales per year
# column wise , axis = 0

print(np.sum(sales_data, axis=0)) # Note we did not skip the index column

[  15  810  945 1085 1240]


In [67]:
print(np.sum(sales_data[:, 1:], axis=0))

[ 810  945 1085 1240]


In [69]:
# Restaurant wise 
print(sales_data)
print("\n-------restaurant wise sale-----")
print(np.sum(sales_data[:, 1:], axis=1))

[[  1 150 180 220 250]
 [  2 120 140 160 190]
 [  3 200 230 260 300]
 [  4 180 210 240 270]
 [  5 160 185 205 230]]

-------restaurant wise sale-----
[800 610 990 900 780]
