### Numpy learning

##### Notes
- numpy written in C++
- only works with similar data types
- if you change a single element to float in a matrix name.dtype returns float64
- np.where also returns an array like np.array but for elements for which condition is true
- axis 0 is rows. axis 1 is columns

In [1]:
#pip install numpy # un comment if required

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4])  #Needs a list

In [4]:
print(arr_1d)

[1 2 3 4]


In [5]:
arr_2d = np.array([1,2,3], [4,5,6]) # This gives error that "Field elements must be 2- or 3-tuples, got '4'"

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
arr_2d = np.array([[1,2,3], [4,5,6]])

In [ ]:
print("2d array:", format(arr_2d))

In [ ]:
arr_2d

In [ ]:
print("2d array:", arr_2d )

In [6]:
zeros = np.zeros([3,4])
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
ones = np.ones([2,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
full = np.full((2,3),5)
print(full)

[[5 5 5]
 [5 5 5]]


In [9]:
rand = np.random.random((3,3)) # random values vary from 0 to 1
print(rand)

[[0.87494535 0.51079503 0.50747711]
 [0.23330813 0.79924125 0.28197808]
 [0.71160443 0.68621061 0.32637551]]


In [10]:
rang = np.arange(1, 14, 3) # inclusive 1 non-inclusive 14 in step of 3
rang

array([ 1,  4,  7, 10, 13])

#### vector

In [11]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


#### matrix

In [12]:
mat = np.array([[1,2,3],
                [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


#### tensor or multi dimensional

In [13]:
tens = np.array([[[1,2], [3,4]],
                [[5,6],[7,8]]])
print(tens)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Properties

In [14]:
tens.shape # 2 element, 2 rows, 2 columns

(2, 2, 2)

In [15]:
tens.ndim # dimension 3-d

3

In [16]:
tens.size # total elements

8

In [17]:
tens.dtype # data type

dtype('int64')

In [18]:
mat.shape

(2, 3)

In [19]:
mat.ndim

2

In [20]:
print(mat)

[[1 2 3]
 [4 5 6]]


#### Operations

In [21]:
# transpose
trans = mat.transpose()
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
# flatten
flat = mat.flatten()
print(flat)

[1 2 3 4 5 6]


In [23]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [24]:
# ravel
raveled = mat.ravel()
print(raveled)

[1 2 3 4 5 6]


In [25]:
print(mat)

[[1 2 3]
 [4 5 6]]


###### flatten(): returns a copy of original arary. ravel() return a view( a reference) of the original array whenever possible. it does not allocate new memory unless it is  has to. 
###### because of this if you modify an element in ravel() ed array original array changes as well (because they share same memory data block)
###### ravel is faster and is just a view of the original array whenever possible

In [26]:
raveled[0] = 99
print(raveled)

[99  2  3  4  5  6]


In [27]:
print(mat)

[[99  2  3]
 [ 4  5  6]]


In [28]:
print(flat)

[1 2 3 4 5 6]


In [29]:
# reshape
reshaped = flat.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


##### More operations

In [30]:
arr = np.arange(0,12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
# Basic slicing
print(arr[1:5]) # basic slicing. Starts from index 1 and end at index 5
print(arr[1:9:3]) # step of 3
print(arr[-4]) # negative indexing

[1 2 3 4]
[1 4 7]
8


In [32]:
# Two dimensinal array
print(mat)
mat.ndim

[[99  2  3]
 [ 4  5  6]]


2

In [33]:
# index by giving row and then column (start from 0th row 0th col)
# 2nd row 3rd column
print(mat[1,2]) 

6


In [34]:
# just second row
print(mat[1])

[4 5 6]


In [35]:
# second column
print(mat[:,1])

[2 5]


###### Sort

In [36]:
unsorted = np.array([4, 8, 6, 2, 6, 2, 7, 5, 2, 3, 9, 5 ])
print(np.sort(unsorted))  # original remains un changed
print(unsorted)

[2 2 2 3 4 5 5 6 6 7 8 9]
[4 8 6 2 6 2 7 5 2 3 9 5]


In [37]:
unsorted2d = unsorted.reshape(3,4)
print(unsorted2d)

[[4 8 6 2]
 [6 2 7 5]
 [2 3 9 5]]


In [38]:
# sort 2-d array
print(np.sort(unsorted2d, axis = 0)) # On columns - axis 0

[[2 2 6 2]
 [4 3 7 5]
 [6 8 9 5]]


In [39]:
print(np.sort(unsorted2d, axis = 1)) # On rows of unsorted2d - axis 1

[[2 4 6 8]
 [2 5 6 7]
 [2 3 5 9]]


##### Filter and Filter by mask

In [40]:
ranks = np.array([1,2,3,4,5,6,7,8,9,10])
evenRanks = ranks[ranks % 2 == 0]  # filter only even number
print(evenRanks)

[ 2  4  6  8 10]


In [41]:
# mask
# create mask
mask = ranks > 5
# Now use this directly in filter condition
bigRanks = ranks[mask]
print(bigRanks)

[ 6  7  8  9 10]


In [42]:
# what doses mask represent. Its actually an array of True/False
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

###### where
###### different then mask as 'where' gives same number of elements

In [43]:
# if greater than 5 then multiply it by 3 other wise same number
bigRanksTripled = np.where( ranks > 5, ranks * 3, ranks)
print(bigRanksTripled)

[ 1  2  3  4  5 18 21 24 27 30]


##### masked_where

In [44]:
# hide even numbers
onlyOdds = np.ma.masked_where(ranks % 2 == 0, ranks)
print(onlyOdds)

[1 -- 3 -- 5 -- 7 -- 9 --]


In [45]:
onlyOdds

masked_array(data=[1, --, 3, --, 5, --, 7, --, 9, --],
             mask=[False,  True, False,  True, False,  True, False,  True,
                   False,  True],
       fill_value=999999)

###### Adding and removing data

#### for merge or concatenate two arrays pass them as tuple to concatenate


In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

merged = np.concatenate((arr1, arr2))

print(merged)
type(merged)

[1 2 3 4 5 6]


numpy.ndarray

In [47]:
# compatability
arr1.shape == arr2.shape

True

###### adding new row using vstack, column using hstack

In [48]:
a2darray = np.array([[1,2],[3,4]])
newRow = np.array([[5,6]])

print("Shape of a2darray: ", format(a2darray.shape))

threeRows = np.vstack((a2darray, newRow))
print(threeRows)
print("\n Shape of threeRows: ", format(threeRows.shape))


Shape of a2darray:  (2, 2)
[[1 2]
 [3 4]
 [5 6]]

 Shape of threeRows:  (3, 2)


In [49]:
# Now add a column using hstack
newCol = np.array([[7], [8], [9]])

withThirdColumn = np.hstack((threeRows, newCol))
print(withThirdColumn)
print("\n Shape of withThirdColumn ", format(withThirdColumn.shape))

[[1 2 7]
 [3 4 8]
 [5 6 9]]

 Shape of withThirdColumn  (3, 3)


##### delete 

In [50]:
deleted3DArray = np.delete(withThirdColumn, 1, 1) # here 1nth element from axis 1(column).
print(deleted3DArray)

[[1 7]
 [3 8]
 [5 9]]


In [51]:
#  axis 0 is rows
deleted0Axis = np.delete(withThirdColumn, 1, 0)
print(deleted0Axis)

[[1 2 7]
 [5 6 9]]
